#:schema ./multimr.schema.json
# "$schema" = "https://github.com/h0uter/multimr.schema.json"

reviewers = ["alice", "bob", "carol"]

labels = { feat = "type::feature", fix = "type::fix" }

working_dir = "src_repos"